### ISSUE TITLE
[Suggestion] Generate multiple resources at once

### ISSUE THREAD

**Issue by Lobosque** [paknahad/jsonapi-bundle#1]
Suggestion: keep asking for another Entity name until the user returns blank!

PS: This bundle is amazing! Keep up the good work!

**Comment by paknahad** [comment]
thanks for the suggestion
unfortunately, this bundle is not meant to handle entity creation.
this should be handled by "[Symfony maker bundle](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html)"
