### ISSUE TITLE
Support sorting

### ISSUE THREAD

**Issue by mnugter** [paknahad/jsonapi-bundle#17]
I checked but I think sorting is not supported yet right?

Fortunately there is a spec for sorting:
https://jsonapi.org/format/#fetching-sorting

I'll try and see if I can make a PR for this.

**Comment by mnugter** [comment]
I started a branch with some refactoring. This is a start at separating out the field logic from the Finder itself.

Next steps I want to do:
1. Move out relation handling from Finder.
2. I think alter the FinderCollection solution to a more generic solution in which various services can manipulate the query. I'm not completely sure on this though.

Note that it's still a work in progress and that I'm not completely happy yet, just wanted to share the progress :)

**Comment by mnugter** [comment]
Another big step in the refactor, only 1 thing to go for a minimal refactor: move relations out of the Finder.

Reasons for my refactoring:

- I tried to limit the amount of class creations with new, this makes testing code hard / impossible.It would be ideal to remove all new statements but I tried to keep my scope managable.
- I tried to limit classes to doing the least amount of things
- Reduce required duplicate code for sorting
- Make the generated controller simpler in code while keeping the current flexibility (access to the query via getQuery())

Biggest changes:
- I added a FieldManager class, this class handles all field logic (was in Finder class before) and registering relations.
- I used the ResourceCollection class as the central handling point for the index request. 

I tested all my changes manually by:
- Request index for entity
- Request index for entity with filter on base entity
- Request index for entity with filter on relation
- Request index with include=
- Request index with altered paging

I would be very nice and good for this library to add automated tests.

Btw: as this refactor breaks with compatibility I would recommend tagging a release with this change as 2.x instead of 1.x.

**Comment by mnugter** [comment]
After the refactor adding sorting was actually quite easy. I needed some small aditional fixes on the refactor but sorting is now working!

It conforms to the JSON API standard. I added instructions in the README for the sorting.

As stated before: If you decide to commit this (which I would like very much as I don't want to start using my own fork) I would recommend tagging a new version with 2.0-alpha. I would only move out of alpha phase once your confident the API will not change and there is complete test-coverage to ensure BC.

Let me know what you think!

**Comment by mnugter** [comment]
PR: #18

**Comment by mnugter** [comment]
Github is acting a little weird, my comments keep disappearing, as does my PR. Lets try again.

There should be a PR #18 with sorting enabled. I documented the feature in README.md.

As said before, if you decide to merge the PR I would recommend tagging it as 2.0-alpha. I would only move to beta once your confident about the API and have test-coverage.

Please let me know what you think!

**Comment by paknahad** [comment]
Thank you for your PR.
I really like it. just, I found some little issues, I leave my comments on codes.

yes, we need more test. definitely, it's necessary.
also, we need PHP_CodeSniffer for checking code style (at least [PSR 1 & 2](https://www.php-fig.org/psr/psr-2/))

about tagging, I agree with you, it's OK

**Comment by mnugter** [comment]
I reviewed the code, I had some trouble with phpStorm ignoring the vendor directory. I ran the code sniffer for symfony and fixed all problems, as well as the small mistake in the template.

Please let me know if it's ok like this!

**Comment by paknahad** [comment]
Thank you very much.

I'm going to merge this PR then I'll tag it as 2.0.0-alpha

**Comment by mnugter** [comment]
Awesome, thanks!
