### ISSUE TITLE
Using relationship

### ISSUE THREAD

**Issue by waghanza** [paknahad/jsonapi-bundle#21]
Hello @paknahad @kocsismate,

When I write a relationship method in my transformer

~~~php
public function getRelationships($order): array
    {
        return [
            'customer' => $order->getCustomer(),
        ];
    }
~~~

in **yin** `AbstractResourceTransformer`  the variable `$relationshipCallback` 
https://github.com/woohoolabs/yin/blob/65e6bc15aa6efdcef8c17a4b246ba581192f5b7b/src/JsonApi/Transformer/AbstractResourceTransformer.php#L204

is an object (a **proxy** one) handled by `symfony`.

**yin** require a `string`, no ?

Regards,

**Comment by kocsismate** [comment]
Hi,

No-no! The `getRelationships()` method must return an array of `callback`s (in the most of the cases, anonymous functions will do it) which return a Relationship object. So your example has to be fixed this way:

```php
public function getRelationships($order): array
    {
        return [
            "customer" => function (array $order) {
                return
                    ToOneRelationship::create()
                        ->setData(
                            function () use ($order) {
                                return $order->getCustomer();
                            },
                            new CustomerResourceTransformer()
                        );
            }
        ];
    }
```

I know that it is a bit complex, but the JSON:API spec is also a bit too complex. Have a look at the [examples](https://github.com/woohoolabs/yin/tree/65e6bc15aa6efdcef8c17a4b246ba581192f5b7b/examples) directory, I tried to add quite some examples there.

**Comment by kocsismate** [comment]
@waghanza, Oops, I made a mistake in my example (now, I updated it). I copy-pasted an example originally, where the `ToOneRelationship::setDataAsCallable()` method was used, but I forgot to adapt the code to the `ToOneRelationship::setData()` method.

**Comment by waghanza** [comment]
@kocsismate There is no `create` method for `ToOneRelationship`

**Comment by kocsismate** [comment]
You have to use the `WoohooLabs\Yin\JsonApi\Schema\Relationship\ToOneRelationship` ;)

**Comment by waghanza** [comment]
@kocsismate of course ;-) I have this

**Comment by kocsismate** [comment]
@waghanza Please have a look at it again, because it is there for almost 2 years: https://github.com/woohoolabs/yin/blob/159c654e1dcf933eb2ac1eea9082366737ec8171/src/JsonApi/Schema/Relationship/AbstractRelationship.php#L46

**Comment by waghanza** [comment]
@kocsismate yep. I was using wrong `use`

**Comment by kocsismate** [comment]
@waghanza Yes, that's why I wanted to clarify the fully qualified class name. I'm glad that the problem got sorted out!
