### ISSUE TITLE
Checking Authority in query builder

### ISSUE THREAD

**Issue by paknahad** [paknahad/jsonapi-bundle#22]
For security reasons, we have to limit the client in filtering some fields & tables.
I would prefer to check client access to tables and fields in voters.

@mnugter what do you think? let me know, please.

**Comment by mnugter** [comment]
Interesting case. So you want some users to see the full entities with all fields and other users with only a limited set of fields for the entities?

That's actually something I did a limited amount of research in but I didn't find anything satisfactory yet.
I seems that the Symfony ACL bundle would be able to help with this use case but I'm not sure if it would be complete.

I would say it's outside of the scope of this bundle by the way. I think you'd want to handle this on a higher level, maybe as close as possible to doctrine itself.

**Comment by mnugter** [comment]
I have though about it a little and maybe the answer is somewhere in the entity repositories.

I would have a separate bundle for this which you could plugin to the entity repository. Tag each field in your entity for which roles have access or maybe use a Voter pattern. the EntityRepository will make sure the fields that are selected are filtered based on the permissions.

Not sure on the exact implementation though. Hope the suggestions help!

**Comment by paknahad** [comment]
Yes. I have already done it. I added voter, so the user is able to control all actions, fields, and relations.
please take a look on my last commits.
I just want the ability to limit query fields based on user's need.

**Comment by mnugter** [comment]
2 more general suggestions:

I'm in doubt about including it in this bundle as it greatly increases the scope outside of the json-api specification and forces the use of the voters, a solution with a separate bundle would have been better I think as it would promote separation of concern and as a user of this bundle I only get what I want (a JSON API solution).
I would also recommend using feature branches for new features as it makes reviewing and fine-tuning a lot easier.

On the change:
I like the idea to solve this problem with Voters and the implementation looks good, overall the code looks good. I'm not on my developer computer and that makes it a little difficult to really check the changes. Things I think should be possible to be improved:
- I think it should be possible to have more generic base classes and less generated code in the templates. In part maybe with php reflection.
- I like the InputOutputManager class and the fact there is a factory class for creating instances, maybe it's possible to convert it to a symfony factory service?
- In general: to limit the scope of this bundle for Voter implementation maybe support could be added in that the validation would accept setting Voter instances. You could move the actual voters out of this bundle (maybe make a separate bundle for a basic set of Voters there).
- Does the current implementation check on the fields of an included relation? Not sure as I can't test the code on this computer.

**Comment by paknahad** [comment]
Thanks. It's very kind of you.
I think you're right, I'm going to create a new bundle to manage security things

And another subject that is not related to this project, if it does not matter, I wanna have a private conversation with you.
My email address is in my profile.

**Comment by paknahad** [comment]
Thanks. it's very kind of you.

Unfortunately, I couldn't find a practical way to implement this feature on a separate bundle.
I need this feature, also I'm so busy and I can't spend more time at this moment.

I'll be happy if you could find a better way.
