### ISSUE TITLE
Workflow for Updating Entities?

### ISSUE THREAD

**Issue by MrAvantiC** [paknahad/jsonapi-bundle#25]
Hi,

first of all: Thanks for the amazing bundle. Really impressive to generate a JSON-API right out of the box!

I have 2 questions though:
**First:**
I create an User-Entity with `php bin/console make:entity User` and generate the API for it with `php bin/console make:api User`. Works great! 

Now I want to modify the User-Entity later on using the update-functionality of `php bin/console make:api User`. The API does not represent these changes though.
If I run `php bin/console make:api User` again I get errors that the files are already existing (e.g. "[ERROR] The file "src/Controller/UserController.php" can't be generated because it already exists").

What is the proposed way to update the api? 
If I just delete the controller and the `JsonApi`-directory that the command created it works fine. 
But I'm not sure if this is the way to go or am I missing something? :)

**Second:**
This is kind of related to my first question. If I don't want to display all fields of an Entity in the API-Response, I just adjust the `getAttributes()`-method in the related `ResourceTransformer`, right? 
But if the only way to update the API when an Entity changes later on is to delete the `JsonApi`-directory this way to restrict the displayed content is quite fragile.

Thanks for you help and the awesome bundle! ;)

**Comment by paknahad** [comment]
Hi

This bundle is following [maker-bundle's](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html) rules. That don't rewrite/regenerate CRUD after generating files.

after making APIs by the maker, you have to change generated files manually.

Thanks :)

**Comment by MrAvantiC** [comment]
Good to know! Thanks ;)
