### ISSUE TITLE
Fatal error on creating swagger collection

### ISSUE THREAD

**Issue by asalisaf** [paknahad/jsonapi-bundle#32]
Hi,

make:api gives below error on running

`Fatal error: Interface 'phootwork\lang\Arrayable' not found in /vendor/paknahad/jsonapi-bundle/src/Collection/Swagger/Swagger.php on line 10`

"phootwork/collection" should be part of "require" section instead of "require-dev". It's needed for generating Swagger doc.

**Comment by paknahad** [comment]
Hi Saeed,

You have missed installing DEV requirements.
```
composer require symfony/maker-bundle phootwork/collection --dev
```

**Comment by nelson6e65** [comment]
How can I recreate Swagger collection if I modified routes?
