### ISSUE TITLE
Reseting JsonApi instance between controllers requests

### ISSUE THREAD

**Issue by krukru** [paknahad/jsonapi-bundle#35]
Hello @paknahad,

thank you for this great Symfony bundle, which saves a lot of time and is the best I could find on symfony and json-api standard.

I started writing functional api tests in Codeception for a project which is using this jsonapi-bundle and I encountered a problem.

In a nutshell, all tests cases after the first one will fail with a "Invalid json" error message. This can be reproduced either by using a `@dataProvider` or by simply having multiple test functions in a single test class. The effect is the same. You can read a detailed description of the issue here https://github.com/woohoolabs/yin/issues/81

The reason being is that [`Paknahad\JsonApiBundle\Controller`](https://github.com/paknahad/jsonapi-bundle/blob/master/src/Controller/Controller.php#L21-L28) is caching jsonapi responses between tests, and the json api responses in the response buffer get mixed up. The same output buffer is reused over and over and this gives a corrupt json after the first test.

Is there some way to disable this caching in test environments or do you have some other suggestion on this issue?

**Comment by krukru** [comment]
Also if someone is interested, a temporary workaround is to add to your tests the following snippet
```php

    public function _after(): void
    {
        $reflectionClass = new ReflectionClass(\Paknahad\JsonApiBundle\Controller\Controller::class);
        $reflectionProperty = $reflectionClass->getProperty('jsonApi');
        $reflectionProperty->setAccessible(true);
        $reflectionProperty->setValue(null);
    }

```

**Comment by paknahad** [comment]
Hi @krukru 

I'm happy to see you're interested in this bundle.
I suppose your problem will be fixed if you use "insulate" method, as in this simple test:

https://github.com/paknahad/jsonapi-bundle/blob/34ecf127a2f38e9aad4a0ecaea03bf2462e751a3/tests/fixtures/ApiCrud/tests/GeneratedApiCRUDTest.php#L15-L25

Please let me know whether it works for you or not?

**Comment by krukru** [comment]
Hi @paknahad.
This indeed also solves the issue!

Unfortunately it does not seem that codeception REST module (which I am using to write tests) exposes the `$client` directly in order to set `insulate()` to true.

For now I will use the workaround using reflection and try to expose insulate in codeception REST module

**Comment by paknahad** [comment]
Hi @krukru 

 This issue has been fixed. just update the bundle.

Thanks.
