### ISSUE TITLE
JsonApiFactory breaks if there is no Request object in RequestStack

### ISSUE THREAD

**Issue by brunozoric** [paknahad/jsonapi-bundle#36]
It seems there are no Request objects in RequestStack when doing OPTIONS (preflight request) on a route that uses your [Controller](https://github.com/paknahad/jsonapi-bundle/blob/master/src/Controller/Controller.php) since it requires JsonApi object and it is created via [factory](https://github.com/paknahad/jsonapi-bundle/blob/master/src/Factory/JsonApiFactory.php#L27).

Quick way to fix this is to check if there is a Request object in RequestStack and if there is not, just create a new, empty one.

I can do a PR if you agree on a fix :)

**Comment by paknahad** [comment]
I don't know what your case is! but I think the OPTIONS request must not handle by a controller. you need merely an event listener to respond to "OPTIONS requests".

remove OPTIONS methods from your routes. you don't need them. just install this bundle: https://github.com/nelmio/NelmioCorsBundle

in case you're going to check by Postman, don't forget "Origin" header in your request.

**Comment by brunozoric** [comment]
I have NelmioCorsBundle installed. Everything worked till 2.1.0 version.
It breaks in dev env because of the profiler. When I set APP_ENV to prod it works.
Before 2.1.0 version JsonApi object was created when requested ( inside a route method ). Profiler does not go through route methods, just constructs the Controller - although I do not know why - not that big of an expert :)

**Comment by paknahad** [comment]
Hi @brunozoric ,

Finally, I managed to regenerate this issue, it will happen if you install symfony/profiler-pack (or create project by symfony/web-skeleton instead symfony/skeleton)

I fixed this issue.

Thanks for reporting :)
