### ISSUE TITLE
Generating json api breaks when using User entity from FOSUser bundle

### ISSUE THREAD

**Issue by brunozoric** [paknahad/jsonapi-bundle#37]
@paknahad Thx for solving last issue :) Here is a new one :)
When using FOSUser bundle and you try to generate json api via make:api it breaks on unique and nullable indexes in $fields array ( [ApiCrud.php#L318](https://github.com/paknahad/jsonapi-bundle/blob/master/src/Maker/ApiCrud.php#L318) )
This is due to mapping xml in FOSUser bundle not having unique and nullable attributes ( [User.orm.xml#L9](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/config/doctrine-mapping/User.orm.xml#L9) ). Probably there are more cases when some bundle does not have those fields defined in xml mapping. It is fixable by setting default value when no unique/nullable index or by setting those fields to unique via UniqueEntity constraint, eg.: `@UniqueEntity(fields={"username"}, message="Username is taken") `
I think preferable way would be that those indexes have some default values that developer can override. I am happy to make a PR if you want :)

**Comment by paknahad** [comment]
You're welcome :)

PR always makes me happy. I'm waiting for that :)

**Comment by brunozoric** [comment]
We solved this issue
