### ISSUE TITLE
Sorter breaks when using Querifier bundle

### ISSUE THREAD

**Issue by brunozoric** [paknahad/jsonapi-bundle#38]
Another thing I found while using your Querifier bundle.
In Querifier bundle sort is expected to be array and in jsonapi bundle it is expected to be a string. Its not a big issue, I have overriden Sorter given by jsonapi bundle to fix it but maybe you can check if sort is array and then do not do the explode().
So basically I check if sort is array in parseSortingString method ( it does not have argument type which actually saves the day - [link](https://github.com/paknahad/jsonapi-bundle/blob/master/src/Helper/Sorter.php#L42) ) and if it is array, just implode it and continue with parent method.
I can do a PR if you want :)

**Comment by paknahad** [comment]
About Qerifier, actually that needs many changes, and I want to refactor that. It may take more time to fix.

Can I have your email address? Mine is in my profile, could you send me an email?
