### ISSUE TITLE
Error Response Formatting

### ISSUE THREAD

**Issue by jakagacic** [paknahad/jsonapi-bundle#40]
Hi!

I noticed that all of the validation errors for attributes array are formatted correctly, but if you send a wrong type, that causes WoohooLabs' exception `ResourceTypeUnacceptable`, you will get an Internal server error with code 500. After digging in to the code, I found that this could be fixed in [`JsonApiErrorHandlerEvent::toErrorDocument`](https://github.com/paknahad/jsonapi-bundle/blob/master/src/EventSubscriber/JsonApiErrorHandlerEvent.php#L99), by calling the exception's `toErrorDocument` method, if the exception is an instance of `JsonApiExceptionInterface`.

What do you think? Is there a better way to do this?

**Comment by paknahad** [comment]
Hi,

Yes, I'll be happy if you fix it.

**Comment by paknahad** [comment]
@jakagacic thank you.

**Comment by jakagacic** [comment]
@paknahad I am happy to contribute. Thank you for this great bundle.
