### ISSUE TITLE
Class WoohooLabs\Yin\JsonApi\Document\AbstractCollectionDocument is deprecated

### ISSUE THREAD

**Issue by pusle** [paknahad/jsonapi-bundle#44]
I tried this excelent bundle today and got a deprecation warning.

Class WoohooLabs\Yin\JsonApi\Document\AbstractCollectionDocument is deprecated, use WoohooLabs\Yin\JsonApi\Schema\Document\AbstractCollectionDocument instead.

```
[▼
  "exception" => SilencedErrorContext^ {#874 ▶}
]

{▼
  /.../vendor/woohoolabs/yin/src/JsonApi/Document/AbstractCollectionDocument.php:13 {▶}
  /.../src/JsonApi/Document/User/UsersDocument.php:12 {▼
    ›  */
    › class UsersDocument extends AbstractCollectionDocument
    › {
  }
}
```

**Comment by paknahad** [comment]
Hi,

Thank you for reporting.
You can use version 3 of this bundle, to avoid this warning.
