### ISSUE TITLE
Ambiguous error message

### ISSUE THREAD

**Issue by markopaden** [paknahad/jsonapi-bundle#45]
I was trying to generate Api for User class, and I was getting this error:
```
[ERROR] "" is not valid as a PHP class name (it must start with
         a letter or underscore, followed by any number of      
         letters, numbers, or underscores)  
```
As it turns out, my repository class annotation was missing in User class:
``` * @ORM\Entity(repositoryClass="App\Repository\UserRepository")```
Wouldn't it be better if the error said "Repository class not found" or something like that?

**Comment by paknahad** [comment]
This error is shown by maker-bundle, and it's not related to this bundle.
https://github.com/symfony/maker-bundle/blob/c4388410e2fb6321e77c5dd6e3cb2dba821f9fe6/src/Validator.php#L57
