### ISSUE TITLE
Support more advanced filtering in query

### ISSUE THREAD

**Issue by mnugter** [paknahad/jsonapi-bundle#5]
The current filtering only supports a limited set of possibilities.

I would love the ability to have advanced filtering options available like AND/OR, greater than, etc.

I have done some research and JSON API does not dictate any standards and nothing is close to beeing the default implementation.

Some interesting options for standards I found:
- https://gist.github.com/e0ipso/efcc4e96ca2aed58e32948e4f70c2460
- https://github.com/andreas-glaser/doctrine-rql
-- RQL is an extension of FIQL https://fiql-parser.readthedocs.io/en/stable/usage.html

To me searching for a standard outside JSONAPI makes the most sense for implementation although even there there doesn't seem to be a reliable standard.

**Comment by paknahad** [comment]
Thanks for the suggestion.
it's a very good idea, I like [this one](https://gist.github.com/e0ipso/efcc4e96ca2aed58e32948e4f70c2460).
but I think it's too complicated. I'm looking for the simplest way to get this feature

**Comment by mnugter** [comment]
The easiest way forward is the best way forward to me. If there is a library doing the heavy work that would be awesome.

I have been doing some more research into this and it really seems there is no accepted standard and nothing seems to be emerging. It seems weird for the json-api spec to miss this as to me it's a fundamental part of an API specification.

I did find the oData standard but that describes a full format for an API and we're only looking for a query string filter format.
Other types of backends describe an advanced format as well, like elastic search. The format is interesting but there are no libraries available.

The more I think about it, it should be best if this package would not be too opinionated on which filter structure should be used. If would therefore be very nice to be able to plug in different Finders which can handle different types of filtering. In a few days I'm going to research what would be the best way to make in pluggable. As I need advanced filtering for a project (range filter and aggregated fields filter) I'll try to make a PR with the changes as I described.

First step would be to make the Finder pluggable, I would like to maintain the current version as it's really simple to use. Adding variants for the filtering by either separate bundles or package them in this bundle would be fine, not really sure on preference here.

Choices to make in making the Finder pluggable:
1. Will it be something you can configure (1 active Finder at the time)
2. Will it be choosable from the URL (type=basic, type=rql, etc)
3. Will it be like a strategy pattern, having more finders active at the same time.

Options I found for different filtering types:
- JSON API Fancy Filters.md
-- No library available.
-- Library could be created separately based on the code in the Drupal module. Would be awesome if they could move to using the created library as well.
- doctrine-rql
-- Library available https://github.com/andreas-glaser/doctrine-rql
-- Integration extremely simple, literally 1 line of code.
- oDAta
-- Not only a filter-format standard
-- No suitable library found.
- Custom
-- Lots of work.

**Comment by mnugter** [comment]
i created a fork with pull request for this issue. It doesn't actually add any more advanced filters but it's a step towards it.

Please review my PR and let me know if there is anything I should change!

https://github.com/paknahad/jsonapi-bundle/pull/7

**Comment by mnugter** [comment]
I added comments in the PR to clarify the changes I have made, I hope that helps in understanding the code.

**Comment by paknahad** [comment]
thanks for your PR
I'll check it as soon as possible.

today I had free time and planned a new one
please check this and let me know your opinion:

### Simple query

simple query makes by this structure:
```http request
url?filter[FIELD_NAME]=VALUE
```
Example:
```http request
http://example.com/books?filter[title]=php&filter[author.name]=hamid
```
SQL:
```sql
SELECT * FROM books AS b INNER JOIN authors AS a ...
WHERE
    b.title = 'php'
    AND
    a.name = 'hamid'
```

### Advanced query:
**1- Define conditions.**
```http request
url?filter[CONDITION NAME][FIELD NAME][OPERATOR]=VALUE
```
**2- Combine these conditions together.**
```http request
url?filter[CONDITION NAME][COMBINE]=CONDITIONS SEPARATED BY “,”
```

- **Condition name**_(optional)_ : An identifier for using in combinations, must be started by “_”  and followed by AlphaNumeric characters
- **Operator name**_(optional)_ : Name of an operator such as _eq, _not_eq, _in, _gt, _lt, _like, _btwn
- **Combine** : use to combine two or more conditions : _cmb_or , _cmb_and

Example:
```http request
books?filter[title]=php&filter[_c1][author.name][_like]=%hamid%&filter[_c2][publish_date][_gt]=2017-1-1&filter[_c3][publish_date][_lt]=2017-6-1]&filter[_c4][_cmb_and]=_c2,_c3&filter[_cmb_or]=_c4,_c1
```
SQL:
```sql
SELECT * FROM books AS b INNER JOIN authors  AS a …
WHERE
    b.title = 'php' 
    AND
    (
        (
            b.publish_date > '2017-1-1'
            AND
            B.publish_date < '2017-6-1'
        )
        OR
        a.name LIKE '%hamid%'
     )
```

**Comment by Krilo89** [comment]
I validated the code and can verify that with the new code it's possible to add advanced filtering. Would be nice if this gets merged to start adding advanced filter functions.

**Comment by mnugter** [comment]
So now that the PR is in we're actually able to provide multiple Finders I think it's maybe better to open new issues to update the README to describe this feature?

Also: it would be possible to move the current Finder out from this package itself and into a separate package. I'd be happy to help out there but I think you'd have to create a new repository first as otherwise the namespace would be mine instead of yours (and it's your code). Should I open a new issue to discuss this?

btw: do you know what the above message with the X means? Are there tests now failing?

**Comment by paknahad** [comment]
I think it's better this finder stay in this project as default finder and others be as optional.
I create a new repository as one of the optional finders: [query_parser](https://github.com/paknahad/query_parser).

yes please open a new issue to update README and also create new PR to update that. because you create this PR and you can explain this better than me.

I checked code's quality by Sensiolabs and found some issues in coding style. it's not very important. I'll fix it as soon as possible.
