### ISSUE TITLE
Default filtering

### ISSUE THREAD

**Issue by Gerben321** [paknahad/jsonapi-bundle#52]
I'm integrating this package and it seems to work great so far! However, I've got one issue that I'm not sure of how to implement it. So for example I want to fetch a list of `Project`s. I do this while I'm logged in with a `User`. Every `Project` is coupled to a `User` in the database. So I'm trying to add a default filter on `Project` like  `WHERE user_id = x` before this package does its magic.

Can this be achieved?

**Comment by paknahad** [comment]
You can use $resourceCollection->getQuery() to fetch generated query and add your custom conditions to it

**Comment by Gerben321** [comment]
Thanks for that. I indeed get the QueryBuilder and I try to alter it with ->setMaxResults(1) or ->where() or ->andWhere to try if anything changes, but nothing happens. I guess this is logical since it's only a getter, but how do I manage to set the changes?

**Comment by paknahad** [comment]
I fixed this issue.
you can find the documentation here: https://github.com/paknahad/jsonapi-bundle#setting-a-default-filter-on-the-indexaction
