### ISSUE TITLE
Does this bundle works with Doctrine ODM?

### ISSUE THREAD

**Issue by smtlab** [paknahad/jsonapi-bundle#64]
First of all, thank you for making this much-needed Symfony bundle.

So I am trying to execute this command `php bin/console make:api` seems like it doesn't recognize MongoDB ODM Documents.

So my question is does it only work with ORM currently?

**Comment by paknahad** [comment]
Thanks for your interest.

This bundle is based on [makerBundle](https://github.com/symfony/maker-bundle) and there is no support for MongoDB.

it will be greate if someone can contribute it.
