### ISSUE TITLE
Create new release to allow use bundle in php 8

### ISSUE THREAD

**Issue by mohamed-akef** [paknahad/jsonapi-bundle#79]
I created [this](https://github.com/paknahad/jsonapi-bundle/pull/77) PR to add support for PHP 8, but you didn't create a new release for it.
Can you please create a new release for it?

**Comment by mohamed-akef** [comment]
@paknahad I can't upgrade my application because it depends on your package, please can you create a new release?

**Comment by paknahad** [comment]
Done
