### ISSUE TITLE
Unable to filter integer fields with % when getCount() is used

### ISSUE THREAD

**Issue by nelson6e65** [paknahad/jsonapi-bundle#85]
`?filter[numeric_field]=5%`

I get this error: 
> Conversion failed when converting the nvarchar value '5%' to data type int.

This seems to be related with COUNT; **this occurs when using `$paginator->getCount()` in the documents' collection**:

>SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_11 FROM (SELECT p0_.numeric_field AS numeric_field_0, [...] FROM patients p0_ WHERE p0_.numeric_field = ?)[...]

It's using `=` instead of `like`.

This is a restriction imposed in Finder, to only use "like" on strings:

https://github.com/paknahad/jsonapi-bundle/blob/c62899c59f29ae7c748cc2e0b740a1ef85695b8f/src/Helper/Filter/Finder.php#L109-L111

**Comment by nelson6e65** [comment]
Where is calculated this `$fieldMetadata['metadata']['type']` to add a workaround to set it to string in the meantime?

**Comment by nelson6e65** [comment]
If I remove that restriction, it works:

```diff
-if ('string' === $fieldMetadata['metadata']['type'] && false !== strpos($value, '%')) {
+if (false !== strpos($value, '%')) {  
    return 'LIKE'; 
}
 ```

**Comment by paknahad** [comment]
Hi nelson
Are you sure about that? it shouldn't work!
which database do you use?
At least I'm sure about PostgreSQL, you need to cast the column type to string

**Comment by nelson6e65** [comment]
Hi, @paknahad. I'm using Microsoft SQL Server. The problem is only on count(). 

It is an integer field. If I change it to string in the entity, it works, but the field need to be integer.

Changing the line above (https://github.com/paknahad/jsonapi-bundle/issues/85#issuecomment-1003388156) the filtering seems to work properly with integer.

**Comment by nelson6e65** [comment]
@paknahad I try to use https://github.com/paknahad/jsonapi-querifier-bundle for more advanced finder service, but I get the same problem I had with the default Finder.

BTW, [jsonapi-querifier-bundle](https://github.com/paknahad/jsonapi-querifier-bundle) is compatible with the default Finder's `filter`? I mean, I can switch to the new one without making a refactor.

**Comment by paknahad** [comment]
this bundle is supposed to work with every RDBMS. so i can't make a change that only works on MS-Sql

yes. you don't need to make any change. just install the querifier bundle

**Comment by nelson6e65** [comment]
I ended by using `_like` explicitly using that finder.

For the default finder, I was able to workaround as I explained above.

Yes. I don't know why Microsoft turn _"special"_ some of its Software. 😅


Thanks, anyway for this tools. 🤩
