### ISSUE TITLE
Transformer not generated

### ISSUE THREAD

**Issue by steveclifton** [paknahad/jsonapi-bundle#86]
Hey, first time using this bundle so hopefully im not missing something super obvious with this..

It appears that there is a Transformer missing when I run the `make:api` command. 
The relationship is below - but when trying to `getRelationships()` - the `AgentPhoneResourceTransformer` is missing

Is this something I am doing wrong? 

Thanks!

```
#[ORM\Entity(repositoryClass: AgentRepository::class)]
class Agent {

    ... code

    #[Groups(['agent'])]
    #[OneToMany(
        mappedBy: 'agent',
        targetEntity: AgentPhone::class)
    ]
    private $phones;

}

#[ORM\Table(name: 'phone')]
#[ORM\Entity(repositoryClass: AgentPhoneRepository::class)]
#[ORM\HasLifecycleCallbacks]
class AgentPhone {
    
    ... code

    #[ManyToOne(targetEntity: Agent::class, inversedBy: 'phones')]
    #[JoinColumn(name: 'associated_id', referencedColumnName: 'id')]
    private ?Agent $agent;

}
```

<img width="779" alt="image" src="https://user-images.githubusercontent.com/14119296/152938196-a37e1932-2679-463b-af28-bca18a93cd1d.png">

**Comment by paknahad** [comment]
Hi Steve

did you run ```make:api``` command for both entities? I guess you miss run it for ```AgentPhone``` entity

**Comment by steveclifton** [comment]
Ah right I hadnt created a controller for AgentPhone (as it is updated via agent)
I will keep this in mind for future - Thank you!
